Repository canonical/github-runner-operator, pull requests merged in 2023-12, with the labels that each got.

#150 Update documentation
  docs/explanation/charm-architecture.md
  docs/how-to/change-path.md
  docs/how-to/change-token.md
  docs/how-to/configure-denylist.md
  docs/how-to/contribute.md
  docs/how-to/repo-policy.md
  docs/how-to/run-on-lxd.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/tutorial/managing-resource-usage.md
  docs/tutorial/quick-start.md
Labels: documentation, trivial, Libraries: Out of sync

#158 feat: ARM64 support
  docs/explanation/arm64.md
  docs/how-to/deploy-on-arm64.md
  docs/reference/arm64.md
  src-docs/charm_state.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src/charm_state.py
  src/runner.py
  src/runner_manager.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
Labels: complex, Libraries: Out of sync

#161 Pin aproxy version to revision 6
  src/runner.py
Labels: trivial, Libraries: Out of sync

#149 Add workflow for building runner image
  .github/workflows/e2e_test.yaml
  charmcraft.yaml
  docs/explanation/charm-architecture.md
  scripts/build-image.sh
  src-docs/charm_state.py.md
  src-docs/github_client.py.md
  src-docs/lxd.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_manager_type.py.md
  src-docs/runner_type.py.md
  src/charm.py
  src/github_client.py
  src/lxd.py
  src/runner.py
  src/runner_manager.py
  src/runner_manager_type.py
  src/runner_type.py
  tests/integration/helpers.py
  tests/integration/test_charm_one_runner.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
  tox.ini
Labels: trivial, Libraries: Out of sync

#165 Bug fix: Increase the disk size for building VM image
  scripts/build-image.sh
Labels: bug, trivial, Libraries: Out of sync

#160 Retrieve logs from crashed runners
  .github/workflows/e2e_test.yaml
  .github/workflows/workflow_dispatch_crash_test.yaml
  docs/explanation/charm-architecture.md
  docs/how-to/integrate-with-cos.md
  docs/index.md
  docs/reference/cos.md
  src-docs/lxd.py.md
  src-docs/metrics.py.md
  src-docs/runner_logs.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_manager_type.py.md
  src-docs/runner_metrics.py.md
  src/lxd.py
  src/metrics.py
  src/runner_logs.py
  src/runner_manager.py
  src/runner_manager_type.py
  src/runner_metrics.py
  templates/start.j2
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_metrics.py
  tests/unit/conftest.py
  tests/unit/test_metrics.py
  tests/unit/test_runner_logs.py
Labels: trivial, Libraries: Out of sync

#164 Log job queue duration
  .flake8
  docs/reference/cos.md
  src-docs/errors.py.md
  src-docs/github_client.py.md
  src-docs/github_metrics.py.md
  src-docs/github_type.py.md
  src-docs/metrics.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_metrics.py.md
  src/errors.py
  src/github_client.py
  src/github_metrics.py
  src/github_type.py
  src/grafana_dashboards/metrics.json
  src/metrics.py
  src/runner_manager.py
  src/runner_metrics.py
  tests/integration/test_charm_metrics.py
  tests/integration/test_charm_scheduled_events.py
  tests/unit/conftest.py
  tests/unit/test_github_client.py
  tests/unit/test_github_metrics.py
  tests/unit/test_runner_manager.py
  tests/unit/test_runner_metrics.py
Labels: trivial, Libraries: Out of sync

#168 Rename integration test workflow file
  .github/workflows/integration_test.yaml
Labels: bug, trivial, Libraries: Out of sync

#169 Improve token config description
  config.yaml
Labels: trivial, Libraries: Out of sync

#167 Fix proxy usage of npm during build image
  scripts/build-image.sh
  src-docs/runner_manager.py.md
  src/runner_manager.py
  templates/env.j2
Labels: trivial, Libraries: Out of sync

#173 Fix Job Queue Duration Panel
  src/grafana_dashboards/metrics.json
Labels: bug, trivial, Libraries: Out of sync

#174 Sync disk prior to publishing image
  scripts/build-image.sh
  src/runner_manager.py
Labels: trivial, Libraries: Out of sync
