Repository canonical/github-runner-operator, pull requests merged in 2023-08, with the labels that each got.

#104 Add ppa for proposed kernel release
  src/charm.py
Labels: trivial, urgent

#108 Automatically add LXD instance name to NO_PROXY
  src/runner.py
Labels: bug, trivial

#109 Update maintainers to new format
  metadata.yaml
Labels: trivial

#110 Flush runner during install hook as temp fix for juju issue.
  src/charm.py
Labels: bug, trivial

#113 Add support for push event
  .github/workflows/e2e_test.yaml
  .github/workflows/push_test.yaml
  templates/pre-job.j2
Labels: trivial
