Repository canonical/github-runner-operator, pull requests merged in 2023-10, with the labels that each got.

#99 Integration test for network access of runner
  tests/integration/helpers.py
  tests/integration/test_charm.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_no_runner.py
Labels: trivial

#131 Remove LXD profile prior to retrying creating LXD instance
  src-docs/lxd.py.md
  src/lxd.py
  src/runner.py
  tests/integration/test_charm.py
Labels: bug, trivial

#135 Revert to using GA kernel
  src/charm.py
Labels: trivial, Libraries: OK

#137 Add beta channel as option for promote charm
  .github/workflows/promote_charm.yaml
Labels: trivial, Libraries: OK

#132 Feat/operator workflow integration test
  .github/workflows/integration_tests.yaml
  scripts/pre-integration-test.sh
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_charm_one_runner.py
Labels: trivial, Libraries: OK

#139 ci(digest): Add digest pinning
  renovate.json
Labels: trivial, Libraries: OK

#140 Rename the Grafana Dashboard directory
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: OK

#136 COS integration: Extract runner metrics
  scripts/pre-integration-test.sh
  src-docs/errors.py.md
  src-docs/metrics.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_metrics.py.md
  src-docs/runner_type.py.md
  src-docs/shared_fs.py.md
  src/errors.py
  src/grafana_dashboards/metrics.json
  src/metrics.py
  src/runner.py
  src/runner_manager.py
  src/runner_metrics.py
  src/runner_type.py
  src/shared_fs.py
  templates/pre-job.j2
  templates/start.j2
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_metrics.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_one_runner.py
  tests/unit/conftest.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
  tests/unit/test_runner_metrics.py
  tests/unit/test_shared_fs.py
  tox.ini
Labels: trivial, Libraries: OK

#138 Feat/use docker registry cache
  .github/workflows/integration_tests.yaml
  config.yaml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/errors.py.md
  src-docs/firewall.py.md
  src-docs/github_type.py.md
  src-docs/lxd.py.md
  src-docs/repo_policy_compliance_client.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_type.py.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/firewall.py
  src/github_type.py
  src/lxd.py
  src/repo_policy_compliance_client.py
  src/runner.py
  src/runner_manager.py
  src/runner_type.py
  templates/env.j2
  templates/pre-job.j2
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_one_runner.py
  tests/integration/test_self_hosted_runner.py
  tests/unit/test_runner.py
Labels: trivial, Libraries: OK
