Repository canonical/github-runner-operator, pull requests merged in 2023-11, with the labels that each got.

#141 COS integration: Issue remaining metrics
  src-docs/metrics.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_metrics.py.md
  src/grafana_dashboards/metrics.json
  src/metrics.py
  src/runner_manager.py
  src/runner_metrics.py
  templates/pre-job.j2
  templates/start.j2
  tests/integration/test_charm_metrics.py
  tests/unit/test_runner_manager.py
  tests/unit/test_runner_metrics.py
Labels: trivial, Libraries: OK

#147 Use aproxy and install yarn
  .github/workflows/integration_tests.yaml
  config.yaml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/errors.py.md
  src-docs/lxd.py.md
  src-docs/runner.py.md
  src-docs/runner_type.py.md
  src-docs/utilities.py.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/lxd.py
  src/runner.py
  src/runner_type.py
  src/utilities.py
  tests/integration/test_charm_one_runner.py
  tests/integration/test_charm_with_proxy.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tox.ini
Labels: trivial, Libraries: OK

#151 Use shorter runner names
  src/runner_manager.py
Labels: trivial, Libraries: OK

#153 COS: Add a gauge for active runners
  README.md
  src-docs/metrics.py.md
  src-docs/runner_manager.py.md
  src/grafana_dashboards/metrics.json
  src/metrics.py
  src/runner_manager.py
  tests/integration/test_charm_metrics.py
  tests/unit/test_runner_manager.py
Labels: trivial, Libraries: Out of sync

#156 Fix repo-policy-compliance in integration test
  .github/workflows/integration_tests.yaml
  .github/workflows/workflow_dispatch_failure_test.yaml
  templates/pre-job.j2
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_metrics.py
  tests/integration/test_self_hosted_runner.py
Labels: bug, trivial, urgent, Libraries: Out of sync

#155 Change aproxy listen port to 54969
  src/runner.py
Labels: trivial, urgent, Libraries: Out of sync

#154 Support all other GitHub events
  .github/workflows/e2e_test.yaml
  .github/workflows/schedule_issues_test.yaml
  templates/pre-job.j2
  tests/integration/test_charm_fork_repo.py
Labels: trivial, Libraries: Out of sync
