Repository canonical/github-runner-operator, pull requests merged in 2024-03, with the labels that each got.

#233 Run upload docs to migrate account for docs
  metadata.yaml
Labels: trivial, Libraries: OK

#234 Ability to re-run specific jobs in E2E test
  .github/workflows/e2e_test.yaml
Labels: trivial, Libraries: OK

#237 test: split e2e test into e2e test run and e2e test
  .github/workflows/e2e_test.yaml
  .github/workflows/e2e_test_run.yaml
Labels: trivial, Libraries: OK

#238 Revert remove proxy vars in microstack setup
  scripts/setup-microstack.sh
Labels: trivial, Libraries: OK

#240 Change pie charts to proportion plots over time
  docs/reference/cos.md
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: OK

#244 feat: label config
  config.yaml
  docs/how-to/add-custom-labels.md
  docs/index.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_manager_type.py.md
  src-docs/runner_type.py.md
  src/charm.py
  src/charm_state.py
  src/runner.py
  src/runner_manager.py
  src/runner_manager_type.py
  src/runner_type.py
  tests/integration/test_charm_one_runner.py
  tests/unit/factories.py
  tests/unit/test_charm_state.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
Labels: complex, Libraries: Out of sync

#239 feat: build openstack image
  charmcraft.yaml
  scripts/build-lxd-image.sh
  scripts/build-openstack-image.sh
  scripts/setup-microstack.sh
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/cos.py.md
  src-docs/errors.py.md
  src-docs/github_client.py.md
  src-docs/openstack_manager.md
  src-docs/openstack_manager.py.md
  src-docs/promtail.py.md
  src-docs/runner_manager.py.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/github_client.py
  src/github_type.py
  src/openstack_cloud/__init__.py
  src/openstack_cloud/openstack_manager.py
  src/openstack_manager.py
  src/runner_manager.py
  templates/openstack-userdata.sh.j2
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_openstack.py
  tests/unit/conftest.py
  tests/unit/test_charm_state.py
  tests/unit/test_openstack_cloud.py
  tests/unit/test_openstack_manager.py
  tests/unit/test_runner_manager.py
Labels: complex, Libraries: Out of sync

#245 Bug/config description
  config.yaml
Labels: trivial, Libraries: Out of sync

#246 fix: apt related background service related errors
  scripts/build-lxd-image.sh
  scripts/build-openstack-image.sh
  tests/integration/helpers.py
  tests/integration/test_charm_one_runner.py
Labels: trivial, Libraries: Out of sync
