Repository canonical/github-runner-operator, pull requests merged in 2024-09, with the labels that each got.

#362 fix: add image relation joined framework register
  src/charm.py
Labels: trivial, Libraries: Out of sync

#351 Use the refactored runner manager
  pyproject.toml
  src-docs/charm.md
  src-docs/errors.md
  src-docs/github_client.md
  src-docs/openstack_cloud.md
  src-docs/openstack_cloud.openstack_manager.md
  src-docs/openstack_cloud.openstack_runner_manager.md
  src-docs/runner_manager.md
  src-docs/runner_manager_type.md
  src-docs/runner_type.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/github_client.py
  src/manager/cloud_runner_manager.py
  src/manager/github_runner_manager.py
  src/manager/runner_manager.py
  src/manager/runner_scaler.py
  src/metrics/github.py
  src/openstack_cloud/openstack_manager.py
  src/openstack_cloud/openstack_runner_manager.py
  src/runner.py
  src/runner_manager.py
  src/runner_manager_type.py
  src/runner_type.py
  tests/integration/helpers/common.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_scheduled_events.py
  tests/integration/test_runner_manager_openstack.py
  tests/integration/test_self_hosted_runner.py
  tests/unit/conftest.py
  tests/unit/mock_runner_managers.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_github_client.py
  tests/unit/test_lxd_runner_manager.py
  tests/unit/test_openstack_manager.py
  tests/unit/test_runner.py
  tests/unit/test_runner_scaler.py
Labels: trivial, Libraries: Out of sync

#363 Set proxy_env_vars in OpenStackRunnerManager
  src-docs/openstack_cloud.openstack_runner_manager.md
  src/openstack_cloud/openstack_runner_manager.py
Labels: bug, trivial, Libraries: Out of sync

#367 Fix units with stuck reconciliation
  docs/reference/cos.md
  src-docs/charm.md
  src-docs/event_timer.md
  src/charm.py
  src/event_timer.py
  src/grafana_dashboards/metrics.json
  templates/dispatch-event.service.j2
Labels: bug, documentation, trivial, Libraries: Out of sync

#368 Fix missing reconciliation metric output
  requirements.txt
Labels: bug, trivial, Libraries: Out of sync

#369 Fix SSH health check
  requirements.txt
Labels: bug, trivial, Libraries: Out of sync

#372 feat: health check
  requirements.txt
Labels: trivial, Libraries: Out of sync

#373 test: run test w/ new lib
  requirements.txt
Labels: bug, trivial, urgent, Libraries: Out of sync

#376 Update docs
  docs/explanation/arm64.md
  docs/explanation/charm-architecture.md
  docs/explanation/ssh-debug.md
  docs/how-to/add-custom-labels.md
  docs/how-to/change-path.md
  docs/how-to/change-token.md
  docs/how-to/comply-security.md
  docs/how-to/configure-runner-storage.md
  docs/how-to/debug-with-ssh.md
  docs/how-to/deploy-on-arm64.md
  docs/how-to/integrate-with-cos.md
  docs/how-to/openstack-runner.md
  docs/how-to/run-on-lxd.md
  docs/index.md
  docs/reference/arm64.md
  docs/reference/external-access.md
  docs/tutorial/managing-resource-usage.md
  docs/tutorial/quick-start.md
Labels: documentation, trivial, Libraries: Out of sync

#365 Add changelog for tracking user relevant changes
  .github/pull_request_template.md
  docs/changelog.md
Labels: trivial, Libraries: Out of sync

#380 Add timeout command just before dispatch
  src/charm.py
  templates/dispatch-event.service.j2
Labels: bug, trivial, Libraries: Out of sync

#366 Fix/private endpoint cleanup
  tests/integration/test_runner_manager_openstack.py
Labels: bug, trivial, Libraries: Out of sync

#374 Fix the docs in the quick docs on the label
  README.md
  config.yaml
  docs/tutorial/quick-start.md
Labels: documentation, trivial, Libraries: Out of sync

#377 chore: test timeout
  requirements.txt
Labels: trivial, Libraries: Out of sync

#375 Spawn reactive runner
  docs/changelog.md
  requirements.txt
  src-docs/charm.md
  src-docs/runner_manager.md
  src-docs/runner_manager_type.md
  src/charm.py
  src/charm_state.py
  src/runner_manager.py
  src/runner_manager_type.py
  tests/integration/helpers/common.py
  tests/integration/requirements.txt
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_charm_state.py
  tests/unit/test_lxd_runner_manager.py
  tests/unit/test_runner_scaler.py
Labels: trivial, Libraries: Out of sync

#381 fix: process kill command lib fix
  requirements.txt
Labels: bug, trivial, urgent, Libraries: Out of sync

#382 feat: Job label validation
  requirements.txt
  src-docs/charm.md
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_reactive.py
Labels: trivial, Libraries: Out of sync

#383 Update tutorial
  docs/tutorial/quick-start.md
Labels: documentation, trivial, Libraries: Out of sync
