Repository canonical/github-runner-operator, pull requests merged in 2024-10, with the labels that each got.

#385 fix: add apt-update to userdata
  requirements.txt
  tests/integration/requirements.txt
Labels: trivial, Libraries: Out of sync

#387 Fix regressions for LXD runners
  .github/pull_request_template.md
  .github/workflows/e2e_test_run.yaml
  .github/workflows/scheduled_e2e_test.yaml
  .github/workflows/scheduled_integration_test.yaml
  README.md
  docs/changelog.md
  templates/env.j2
  tests/integration/conftest.py
  tests/integration/test_charm_base_image.py
  tests/integration/test_charm_runner.py
Labels: bug, trivial, Libraries: Out of sync

#388 Fix: Regression on removal of residual dirs
  .github/workflows/integration_test.yaml
  docs/changelog.md
  src-docs/charm.md
  src/charm.py
  tests/integration/test_charm_upgrade.py
Labels: bug, trivial, Libraries: Out of sync

#389 Update docs
  CONTRIBUTING.md
  docs/how-to/contribute.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/integrations.md
  docs/tutorial/quick-start.md
Labels: documentation, Libraries: Out of sync

#390 feat: Adjustments for COS integration for reactive mode
  docs/changelog.md
  docs/reference/cos.md
  requirements.txt
  src-docs/charm.py.md
  src-docs/runner_manager.py.md
  src-docs/shared_fs.py.md
  src/charm.py
  src/grafana_dashboards/metrics.json
  src/runner_manager.py
  src/shared_fs.py
  tests/integration/helpers/charm_metrics.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_runner.py
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_lxd_runner_manager.py
  tests/unit/test_shared_fs.py
Labels: trivial, Libraries: Out of sync

#378 Fix/openstack connection creation
  docs/changelog.md
  requirements.txt
  src-docs/charm_state.py.md
  src/charm.py
  src/charm_state.py
  tests/integration/conftest.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
Labels: trivial, Libraries: Out of sync

#392 fix: add nocreate to logrotate config
  docs/changelog.md
  src/logrotate.py
  tests/unit/test_logrotate.py
Labels: bug, trivial, Libraries: Out of sync

#394 fix: chown of existing reactive runner log dir
  docs/changelog.md
  requirements.txt
Labels: bug, trivial, Libraries: Out of sync

#395 fix: Use datetime.fromisoformat in server uniqueness check
  docs/changelog.md
  requirements.txt
Labels: bug, trivial, urgent, Libraries: Out of sync

#391 fix: shorten instance id
  docs/how-to/openstack-runner.md
Labels: bug, trivial, urgent, Libraries: Out of sync

#396 Include number of expected runners in reconciliation metric
  docs/changelog.md
  docs/reference/cos.md
  requirements.txt
  src/grafana_dashboards/metrics.json
  src/runner_manager.py
  tests/integration/helpers/charm_metrics.py
  tests/integration/test_charm_upgrade.py
  tests/integration/test_reactive.py
  tests/unit/test_lxd_runner_manager.py
Labels: trivial, Libraries: Out of sync
