Repository canonical/github-runner-operator, pull requests merged in 2024-11, with the labels that each got.

#400 docs: change README to follow the template
  README.md
  docs/changelog.md
  tox.ini
Labels: documentation, Libraries: Out of sync

#402 Rename gh action for github-runner-manager
  .github/workflows/test_github_runner_manager.yaml
Labels: trivial, Libraries: Out of sync

#405 Update the src-docs generation to be done just in the root dir
  CONTRIBUTING.md
  generate-src-docs.sh
  github-runner-manager/CONTRIBUTING.md
  github-runner-manager/generate-src-docs.sh
  github-runner-manager/src-docs/errors.md
  github-runner-manager/src-docs/github_client.md
  github-runner-manager/src-docs/manager.cloud_runner_manager.md
  github-runner-manager/src-docs/manager.github_runner_manager.md
  github-runner-manager/src-docs/manager.md
  github-runner-manager/src-docs/manager.runner_manager.md
  github-runner-manager/src-docs/manager.runner_scaler.md
  github-runner-manager/src-docs/metrics.events.md
  github-runner-manager/src-docs/metrics.github.md
  github-runner-manager/src-docs/metrics.md
  github-runner-manager/src-docs/metrics.runner.md
  github-runner-manager/src-docs/metrics.runner_logs.md
  github-runner-manager/src-docs/metrics.storage.md
  github-runner-manager/src-docs/metrics.type.md
  github-runner-manager/src-docs/openstack_cloud.constants.md
  github-runner-manager/src-docs/openstack_cloud.health_checks.md
  github-runner-manager/src-docs/openstack_cloud.md
  github-runner-manager/src-docs/openstack_cloud.openstack_cloud.md
  github-runner-manager/src-docs/openstack_cloud.openstack_runner_manager.md
  github-runner-manager/src-docs/reactive.consumer.md
  github-runner-manager/src-docs/reactive.md
  github-runner-manager/src-docs/reactive.process_manager.md
  github-runner-manager/src-docs/reactive.runner.md
  github-runner-manager/src-docs/reactive.runner_manager.md
  github-runner-manager/src-docs/reactive.types_.md
  github-runner-manager/src-docs/repo_policy_compliance_client.md
  github-runner-manager/src-docs/types_.github.md
  github-runner-manager/src-docs/types_.md
  github-runner-manager/src-docs/utilities.md
  github-runner-manager/tox.ini
  src-docs/github_client.py.md
  src-docs/runner_manager.py.md
  tox.ini
Labels: trivial, Libraries: Out of sync

#406 Comment for local-lxd new track
  README.md
  docs/tutorial/quick-start.md
Labels: trivial, Libraries: Out of sync

#408 fix: Support multiple flavors for "Available Runners" dashboard
  docs/changelog.md
  src/grafana_dashboards/metrics.json
Labels: bug, trivial, Libraries: Out of sync
