Repository canonical/github-runner-operator, pull requests merged in 2024-08, with the labels that each got.

#343 Add test args for openstack interface
  tests/conftest.py
Labels: trivial, Libraries: OK

#344 feat: openstack flush mode
  charmcraft.yaml
  src/openstack_cloud/openstack_manager.py
  src/runner_manager.py
  src/runner_manager_type.py
  tests/integration/helpers/common.py
  tests/integration/test_charm_base_image.py
  tests/integration/test_charm_runner.py
  tests/integration/test_debug_ssh.py
  tests/unit/test_openstack_manager.py
Labels: complex, Libraries: OK

#346 test: add amd64/arm64 testing options
  tests/conftest.py
  tests/integration/conftest.py
Labels: trivial, Libraries: OK

#349 fix: ssh health check failure status report
  src/openstack_cloud/openstack_manager.py
  tests/unit/test_openstack_manager.py
Labels: trivial, Libraries: Out of sync

#345 Refactor of openstack runner manager
  .github/workflows/e2e_test.yaml
  .github/workflows/integration_test.yaml
  pyproject.toml
  src-docs/errors.md
  src-docs/managed_requests.md
  src-docs/metrics.runner.md
  src-docs/openstack_cloud.openstack_cloud.md
  src-docs/openstack_cloud.openstack_manager.md
  src-docs/openstack_cloud.openstack_runner_manager.md
  src-docs/runner_manager_type.md
  src-docs/runner_type.md
  src/errors.py
  src/manager/cloud_runner_manager.py
  src/manager/github_runner_manager.py
  src/manager/runner_manager.py
  src/metrics/runner.py
  src/openstack_cloud/openstack_cloud.py
  src/openstack_cloud/openstack_manager.py
  src/openstack_cloud/openstack_runner_manager.py
  src/runner_manager.py
  src/runner_type.py
  templates/env.j2
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/test_e2e.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/metrics/test_runner.py
  tests/unit/test_openstack_manager.py
  tests/unit/test_runner_manager.py
Labels: trivial, Libraries: Out of sync

#352 change hostname of the runner to mitigate too long hostname
  .github/workflows/e2e_test_run.yaml
  templates/openstack-userdata.sh.j2
Labels: bug, trivial, Libraries: Out of sync

#355 Add max job queue duration panel
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: Out of sync

#357 feat: image-builder openstack creds relation
  src/charm.py
  src/charm_state.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
Labels: trivial, Libraries: Out of sync
