Repository canonical/github-runner-operator, pull requests merged in 2024-05, with the labels that each got.

#274 Fix: Add ubuntu user to adm group for OpenStack runners.
  templates/openstack-userdata.sh.j2
Labels: bug, trivial

#275 Fix dockerhub mirror not used by runner by default
  templates/openstack-userdata.sh.j2
Labels: bug, trivial

#273 Repo-policy-compliance checks for OpenStack
  config.yaml
  src-docs/charm_state.py.md
  src-docs/openstack_manager.md
  src-docs/repo_policy_compliance_client.py.md
  src-docs/runner_manager.py.md
  src/charm_state.py
  src/openstack_cloud/openstack_manager.py
  src/repo_policy_compliance_client.py
  src/runner.py
  src/runner_manager.py
  templates/pre-job.j2
  tests/unit/test_charm_state.py
  tests/unit/test_openstack_manager.py
Labels: complex

#277 Integration tests for COS integration for OpenStack
  .github/workflows/e2e_test_run.yaml
  .github/workflows/push_test.yaml
  .github/workflows/schedule_issues_test.yaml
  .github/workflows/workflow_dispatch_crash_test.yaml
  .github/workflows/workflow_dispatch_failure_test.yaml
  .github/workflows/workflow_dispatch_ssh_debug.yaml
  .github/workflows/workflow_dispatch_test.yaml
  .github/workflows/workflow_dispatch_wait_test.yaml
  pyproject.toml
  src-docs/openstack_manager.md
  src/metrics/runner.py
  src/openstack_cloud/openstack_manager.py
  templates/openstack-userdata.sh.j2
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/helpers/__init__.py
  tests/integration/helpers/charm_metrics.py
  tests/integration/helpers/common.py
  tests/integration/helpers/lxd.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_one_runner.py
  tests/integration/test_charm_scheduled_events.py
  tests/integration/test_charm_with_juju_storage.py
  tests/integration/test_charm_with_proxy.py
  tests/integration/test_debug_ssh.py
  tests/integration/test_openstack.py
  tests/integration/test_openstack_runner.py
  tests/integration/test_self_hosted_runner.py
  tests/unit/metrics/test_runner.py
  tests/unit/test_openstack_manager.py
  tox.ini
Labels: trivial

#279 Not removing busy runner with health check failure
  src-docs/openstack_manager.md
  src/openstack_cloud/openstack_manager.py
Labels: trivial

#281 Fix: Not removing offline runners that are healthy
  src-docs/openstack_manager.md
  src/openstack_cloud/openstack_manager.py
Labels: trivial

#278 chore: rewrite unit tests and fix bugs for charm_state module
  src-docs/charm_state.py.md
  src/charm_state.py
  tests/conftest.py
  tests/unit/test_charm_state.py
Labels: trivial, Libraries: OK

#283 Integration tests for repo-policy-compliance for OpenStack
  src-docs/openstack_manager.md
  src/openstack_cloud/openstack_manager.py
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/helpers/lxd.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_openstack_runner.py
Labels: trivial

#285 OpenStack COS: Ignore online runners when extracting metrics
  src-docs/openstack_manager.md
  src/openstack_cloud/openstack_manager.py
  tests/unit/test_openstack_manager.py
Labels: bug, trivial

#282 docs on fine grained tokens
  config.yaml
  docs/how-to/change-token.md
  docs/index.md
  docs/reference/token-scopes.md
  docs/tutorial/quick-start.md
  src/charm_state.py
Labels: documentation, trivial, Libraries: OK

#286 Add chart displaying available applications
  docs/how-to/debug-with-ssh.md
  docs/reference/cos.md
  src/grafana_dashboards/metrics.json
  src/grafana_dashboards/metrics_longterm.json
  tests/unit/mock.py
Labels: trivial, Libraries: OK

#180 Loki alert rules
  .licenserc.yaml
  docs/reference/cos.md
  src-docs/charm_state.py.md
  src/loki_alert_rules/capacity.rules
  src/loki_alert_rules/failure.rules
Labels: trivial, Libraries: OK
