Repository canonical/github-runner-operator, pull requests merged in 2024-01, with the labels that each got.

#178 Update year in license header to 2024
  actions.yaml
  charmcraft.yaml
  config.yaml
  generate-src-docs.sh
  lib/charms/grafana_agent/v0/cos_agent.py
  metadata.yaml
  pyproject.toml
  scripts/build-image.sh
  scripts/pre-integration-test.sh
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/event_timer.py
  src/firewall.py
  src/github_client.py
  src/github_metrics.py
  src/github_type.py
  src/lxd.py
  src/lxd_type.py
  src/metrics.py
  src/repo_policy_compliance_client.py
  src/runner.py
  src/runner_logs.py
  src/runner_manager.py
  src/runner_manager_type.py
  src/runner_metrics.py
  src/runner_type.py
  src/shared_fs.py
  src/utilities.py
  templates/repo_policy_compliance_service.py
  tests/__init__.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_metrics.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_one_runner.py
  tests/integration/test_charm_scheduled_events.py
  tests/integration/test_charm_with_proxy.py
  tests/integration/test_self_hosted_runner.py
  tests/status_name.py
  tests/unit/__init__.py
  tests/unit/conftest.py
  tests/unit/mock.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_github_client.py
  tests/unit/test_github_metrics.py
  tests/unit/test_metrics.py
  tests/unit/test_runner.py
  tests/unit/test_runner_logs.py
  tests/unit/test_runner_manager.py
  tests/unit/test_runner_metrics.py
  tests/unit/test_shared_fs.py
  tests/unit/test_utilities.py
  tox.ini
Labels: trivial, Libraries: Out of sync

#179 Change built image name to jammy
  .github/workflows/e2e_test.yaml
  scripts/build-image.sh
  src/charm.py
  tests/unit/test_charm.py
Labels: trivial, Libraries: Out of sync

#170 COS integration improvements
  docs/reference/cos.md
  src-docs/github_client.py.md
  src-docs/github_metrics.py.md
  src-docs/github_type.py.md
  src-docs/metrics.py.md
  src-docs/metrics_type.py.md
  src-docs/runner.py.md
  src-docs/runner_metrics.py.md
  src/github_client.py
  src/github_metrics.py
  src/github_type.py
  src/grafana_dashboards/metrics.json
  src/metrics.py
  src/metrics_type.py
  src/runner.py
  src/runner_manager.py
  src/runner_metrics.py
  templates/pre-job.j2
  tests/integration/test_charm_metrics.py
  tests/unit/test_github_client.py
  tests/unit/test_github_metrics.py
  tests/unit/test_runner_metrics.py
Labels: trivial, Libraries: Out of sync

#175 Add integration test with external network disabled and aproxy setup
  .gitignore
  charmcraft.yaml
  scripts/build-image.sh
  scripts/pre-integration-test.sh
  scripts/repo_policy_compliance_service.py
  src-docs/runner_manager.py.md
  src/charm.py
  src/runner.py
  src/runner_manager.py
  tests/integration/helpers.py
  tests/integration/test_charm_with_proxy.py
  tox.ini
Labels: trivial, Libraries: Out of sync

#181 Enable docs automation
  .github/workflows/promote_charm.yaml
Labels: trivial, Libraries: Out of sync

#183 Use instant type for pie charts
  src/grafana_dashboards/metrics.json
Labels: bug, trivial, Libraries: Out of sync

#184 Use percentiles for duration panels
  docs/reference/cos.md
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: Out of sync

#186 Fix: Crashed runner logs not available
  src-docs/errors.py.md
  src-docs/runner_logs.py.md
  src-docs/runner_manager.py.md
  src/errors.py
  src/runner_logs.py
  src/runner_manager.py
  tests/unit/test_runner_logs.py
Labels: bug, trivial, Libraries: Out of sync

#187 Add mount point checks for shared file systems
  src-docs/errors.py.md
  src-docs/runner_manager.py.md
  src-docs/shared_fs.py.md
  src/errors.py
  src/runner_manager.py
  src/shared_fs.py
  tests/integration/test_charm_metrics.py
  tests/unit/test_shared_fs.py
Labels: bug, trivial, Libraries: Out of sync

#189 Dashboard: Remove the file name label in the repo bar gauge
  src/grafana_dashboards/metrics.json
Labels: bug, trivial, Libraries: Out of sync

#176 feat: initial ssh-debug integration
  metadata.yaml
  src/charm.py
  src/charm_state.py
  src/runner.py
  src/runner_manager.py
  src/runner_type.py
  templates/env.j2
  templates/environment.j2
  tests/unit/test_charm_state.py
  tests/unit/test_runner_manager.py
Labels: complex, Libraries: Out of sync

#194 test: add testing workflow yaml
  .github/workflows/workflow_dispatch_ssh_debug.yaml
Labels: trivial, Libraries: Out of sync

#191 Increase reconcile timeout
  src-docs/event_timer.py.md
  src/charm.py
  src/event_timer.py
Labels: trivial, Libraries: Out of sync

#190 Reduce image size by cleaning cache
  scripts/build-image.sh
Labels: trivial, Libraries: Out of sync

#198 test: increase debug ssh workflow timeout
  .github/workflows/workflow_dispatch_ssh_debug.yaml
Labels: Libraries: Out of sync

#196 COS: Add dashboard for long-term metrics
  docs/reference/cos.md
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_type.py.md
  src/grafana_dashboards/metrics_longterm.json
Labels: trivial, Libraries: Out of sync

#193 test: ssh-debug integration test
  .github/workflows/integration_test.yaml
  src/charm.py
  src/charm_state.py
  tests/integration/charm_metrics_helpers.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/requirements.txt
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_debug_ssh.py
  tox.ini
Labels: trivial, Libraries: Out of sync

#201 COS: Add more long-term metrics
  README.md
  docs/reference/cos.md
  src/grafana_dashboards/metrics_longterm.json
Labels: trivial, Libraries: Out of sync

#204 fix: aproxy arm/amd revision fix
  src/runner.py
Labels: trivial, Libraries: Out of sync

#202 test: add secondary tokens
  tests/conftest.py
  tests/integration/conftest.py
Labels: trivial, Libraries: Out of sync

#206 Use Github token in E2E tests
  .github/workflows/e2e_test.yaml
  src-docs/runner.py.md
  tests/integration/conftest.py
Labels: trivial, Libraries: Out of sync

#208 feat: support random choice from tmate relations
  src-docs/charm_state.py.md
  src-docs/runner.py.md
  src-docs/runner_type.py.md
  src/charm_state.py
  src/runner.py
  src/runner_manager.py
  src/runner_type.py
  tests/unit/factories.py
  tests/unit/requirements.txt
  tests/unit/test_charm_state.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
  tox.ini
Labels: enhancement, trivial, Libraries: Out of sync

#211 Allow root disk as runner-storage
  docs/how-to/configure-runner-storage.md
  src/charm.py
  tests/unit/conftest.py
Labels: trivial, Libraries: Out of sync

#209 feat: allow tmate ip addresses to firewall.
  docs/explanation/ssh-debug.md
  src-docs/charm_state.py.md
  src-docs/firewall.py.md
  src-docs/runner_type.py.md
  src/charm.py
  src/charm_state.py
  src/firewall.py
  src/runner.py
  src/runner_manager.py
  src/runner_type.py
  tests/integration/conftest.py
  tests/integration/test_debug_ssh.py
  tests/unit/factories.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_firewall.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
Labels: enhancement, complex, Libraries: Out of sync

#212 feat: auto-update-libs workflow
  .github/workflows/auto_update_libs.yaml
Labels: trivial, Libraries: Out of sync

#214 Do not check license headers in lib directory
  .licenserc.yaml
Labels: trivial, Libraries: Out of sync
