Repository canonical/github-runner-operator, pull requests merged in 2024-12, with the labels that each got.

#411 Juju 3.6
  .github/workflows/e2e_test.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/scheduled_integration_test.yaml
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/test_charm_upgrade.py
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
  tox.ini
Labels: Libraries: Out of sync

#414 fix: Use busy flush on stop
  docs/changelog.md
  github-runner-manager/src-docs/reactive.consumer.md
  src/charm.py
  tests/unit/test_charm.py
Labels: bug, trivial, Libraries: Out of sync

#415 fix: Continue reconciliation after a health check execution error
  docs/changelog.md
  github-runner-manager/src-docs/errors.md
  github-runner-manager/src-docs/manager.cloud_runner_manager.md
  github-runner-manager/src/github_runner_manager/errors.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/health_checks.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
Labels: bug, Libraries: Out of sync, senior-review-required

#412 Allure Integration for Integration Tests
  .github/workflows/integration_test.yaml
  requirements.txt
  tox.ini
Labels: trivial, Libraries: Out of sync

#421 Update idle runners after reconciliation
  docs/changelog.md
  docs/reference/cos.md
  github-runner-manager/src-docs/openstack_cloud.health_checks.md
  github-runner-manager/src-docs/openstack_cloud.openstack_runner_manager.md
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: Out of sync
