Repository canonical/github-runner-operator, pull requests merged in 2024-07, with the labels that each got.

#310 [Docs] Add a note about admin requirement on token scopes.
  docs/reference/token-scopes.md
Labels: documentation, trivial, Libraries: OK

#312 feat: image builder relation
  .github/workflows/integration_test.yaml
  charmcraft.yaml
  docs/how-to/openstack-runner.md
  metadata.yaml
  requirements.txt
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/errors.py.md
  src-docs/openstack_manager.md
  src-docs/runner_manager_type.py.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/openstack_cloud/openstack_manager.py
  src/runner_manager.py
  src/runner_manager_type.py
  tests/integration/conftest.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_no_runner.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_openstack_manager.py
Labels: documentation, trivial, Libraries: OK

#315 chore: image bulider followup
  .pylintrc
  pyproject.toml
  requirements.txt
  src/charm.py
  src/charm_state.py
  src/lxd.py
  src/metrics/events.py
  src/metrics/runner.py
  src/openstack_cloud/__init__.py
  src/openstack_cloud/openstack_manager.py
  src/runner.py
  tests/integration/helpers/common.py
  tests/unit/test_charm.py
Labels: trivial, Libraries: OK

#319 Update token docs to include Actions: read
  docs/reference/token-scopes.md
Labels: bug, documentation, trivial, Libraries: OK

#317 Grafana Dashboard: Combine 3 queries into one
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: OK

#311 Weekly test for legacy features
  .github/workflows/e2e_test.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/scheduled_e2e_test.yaml
  .github/workflows/scheduled_integration_test.yaml
  tests/conftest.py
  tests/integration/conftest.py
Labels: trivial, Libraries: OK

#318 Add workflows for tracks support
  .github/workflows/comment_contributing.yaml
Labels: trivial, Libraries: OK

#322 chore: remove config opts, docs: LXD naming limit
  config.yaml
  docs/how-to/run-on-lxd.md
Labels: documentation, trivial, Libraries: OK

#324 Remove residual empty directories from last revision
  pyproject.toml
  src/charm.py
  src/openstack_cloud/__init__.py
  src/utilities.py
Labels: Libraries: OK

#331 Deal with multiple security groups
  src-docs/logrotate.md
  src-docs/metrics.md
  src-docs/openstack_cloud.openstack_manager.md
  src/openstack_cloud/openstack_manager.py
  tests/unit/test_openstack_manager.py
Labels: bug, trivial, Libraries: OK

#335 Add security group rules by ID
  src-docs/openstack_cloud.openstack_manager.md
  src/openstack_cloud/openstack_manager.py
  tests/unit/test_openstack_manager.py
Labels: bug, trivial, Libraries: OK

#337 Use returned security group for create server
  src-docs/openstack_cloud.openstack_manager.md
  src/openstack_cloud/openstack_manager.py
Labels: bug, trivial, Libraries: OK

#339 Fix scheduled E2E-test
  .github/workflows/scheduled_e2e_test.yaml
Labels: bug, trivial, Libraries: OK

#342 Refine token docs for OpenStack
  docs/reference/token-scopes.md
Labels: documentation, trivial, Libraries: OK

#332 Reactive: Add sigterm handler and process termination.
  src-docs/logrotate.md
  src-docs/metrics.md
  src-docs/reactive.consumer.md
  src-docs/reactive.runner_manager.md
  src/logrotate.py
  src/reactive/consumer.py
  src/reactive/runner_manager.py
  tests/unit/reactive/test_runner_manager.py
  tests/unit/test_logrotate.py
Labels: trivial, Libraries: OK
