Repository canonical/github-runner-operator, pull requests merged in 2024-02, with the labels that each got.

#166 Remove race condition between restart repo-policy-compliance and request of the service
  .github/workflows/integration_test.yaml
  .github/workflows/workflow_dispatch_wait_test.yaml
  src-docs/charm.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_manager_type.py.md
  src/charm.py
  src/runner.py
  src/runner_manager.py
  src/runner_manager_type.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_self_hosted_runner.py
Labels: trivial, Libraries: OK

#216 chore: add build archs
  charmcraft.yaml
Labels: Libraries: OK

#217 Ensure event timer is active
  .github/workflows/e2e_test.yaml
  src-docs/charm.py.md
  src-docs/event_timer.py.md
  src-docs/utilities.py.md
  src/charm.py
  src/event_timer.py
  src/utilities.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_event_timer.py
Labels: bug, trivial, Libraries: OK

#215 docs: fix broken link - how to run on lxd
  docs/tutorial/quick-start.md
Labels: documentation, trivial, Libraries: OK

#218 Use previous token to flush runners
  docs/explanation/charm-architecture.md
  src-docs/charm.py.md
  src-docs/errors.py.md
  src-docs/github_client.py.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_manager_type.py.md
  src/charm.py
  src/errors.py
  src/github_client.py
  src/runner.py
  src/runner_manager.py
  src/runner_manager_type.py
  tests/integration/conftest.py
  tests/integration/test_charm_one_runner.py
  tests/unit/test_runner.py
Labels: bug, trivial, Libraries: OK

#222 Install unzip and gh command functionality.
  .github/workflows/e2e_test.yaml
  scripts/build-image.sh
Labels: Libraries: OK

#224 Dashboard: Flavor filtering
  docs/reference/cos.md
  src/grafana_dashboards/metrics.json
  src/grafana_dashboards/metrics_longterm.json
Labels: bug, trivial, Libraries: OK

#225 Initial OpenStack integration
  .github/workflows/integration_test.yaml
  .gitignore
  config.yaml
  requirements.txt
  scripts/setup-microstack.sh
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/errors.py.md
  src-docs/openstack_manager.py.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/openstack_manager.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/requirements.txt
  tests/integration/test_openstack.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_openstack_manager.py
  tox.ini
Labels: complex, Libraries: OK

#226 Remove unattended-upgrades
  scripts/build-image.sh
Labels: bug, trivial, Libraries: OK

#223 Remove proxy vars when using aproxy
  config.yaml
  docs/explanation/charm-architecture.md
  src-docs/runner.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_type.py.md
  src/charm.py
  src/charm_state.py
  src/runner.py
  src/runner_manager.py
  src/runner_type.py
  templates/env.j2
  templates/environment.j2
  templates/repo-policy-compliance.service.j2
  templates/systemd-docker-proxy.j2
  tests/integration/helpers.py
  tests/integration/test_charm_with_proxy.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
Labels: bug, trivial, Libraries: OK

#199 Refactor configuration to charm state
  config.yaml
  src-docs/charm.py.md
  src-docs/charm_state.py.md
  src-docs/errors.py.md
  src-docs/event_timer.py.md
  src-docs/github_client.py.md
  src-docs/runner_manager.py.md
  src-docs/runner_manager_type.py.md
  src-docs/runner_type.py.md
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/event_timer.py
  src/github_client.py
  src/github_metrics.py
  src/runner.py
  src/runner_manager.py
  src/runner_manager_type.py
  src/runner_type.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_one_runner.py
  tests/integration/test_debug_ssh.py
  tests/integration/test_self_hosted_runner.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_github_client.py
  tests/unit/test_metrics.py
  tests/unit/test_runner.py
  tests/unit/test_runner_manager.py
  tox.ini
Labels: trivial, Libraries: OK

#230 Fix build-image cronjob
  src-docs/runner_manager.py.md
  src/charm.py
  src/runner_manager.py
  tests/unit/test_runner_manager.py
Labels: bug, trivial, Libraries: OK
