Repository canonical/github-runner-operator, pull requests merged in 2024-04, with the labels that each got.

#257 hotfix: support dash label
  src/charm_state.py
  tests/unit/test_charm_state.py
Labels: bug, trivial, urgent, Libraries: Out of sync

#249 test: metrics test flakiness fixes
  src/charm.py
  tests/integration/charm_metrics_helpers.py
  tests/integration/helpers.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_one_runner.py
  tests/integration/test_charm_scheduled_events.py
  tests/integration/test_charm_with_proxy.py
  tests/integration/test_self_hosted_runner.py
Labels: trivial, Libraries: Out of sync

#260 chore: remove test runner image tag
  .github/workflows/e2e_test_run.yaml
Labels: trivial, Libraries: OK

#261 chore: e2e test support noble w/ pipx
  .github/workflows/e2e_test_run.yaml
Labels: trivial, Libraries: OK

#252 Align upgrade_charm hook with install hook
  scripts/build-lxd-image.sh
  src-docs/lxd.py.md
  src-docs/runner_manager.py.md
  src/charm.py
  src/lxd.py
  src/runner_manager.py
  tests/integration/helpers.py
  tests/integration/test_charm_no_runner.py
  tests/unit/conftest.py
  tests/unit/mock.py
  tests/unit/test_charm.py
  tests/unit/test_runner_manager.py
Labels: bug, trivial, Libraries: OK

#262 Add a note about DR recovery
  docs/index.md
Labels: trivial, Libraries: OK

#265 Fix OpenStack runner removal
  src-docs/openstack_manager.md
  src/charm.py
  src/openstack_cloud/openstack_manager.py
  templates/dispatch-event.service.j2
  templates/openstack-userdata.sh.j2
Labels: bug, trivial, urgent

#267 Add external access reference
  docs/index.md
  docs/reference/external-access.md
Labels: trivial, Libraries: OK

#268 Align OpenStack runner with local LXD runners and fix reconcile
  scripts/build-openstack-image.sh
  src-docs/openstack_manager.md
  src/charm.py
  src/openstack_cloud/openstack_manager.py
  templates/openstack-userdata.sh.j2
Labels: trivial

#256 feat: base image config
  .github/workflows/integration_test.yaml
  config.yaml
  docs/how-to/set-base-image.md
  scripts/build-lxd-image.sh
  scripts/build-openstack-image.sh
  src-docs/charm_state.py.md
  src-docs/openstack_manager.md
  src-docs/runner_manager.py.md
  src/charm.py
  src/charm_state.py
  src/openstack_cloud/openstack_manager.py
  src/runner_manager.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_base_image.py
  tests/integration/test_openstack_base_image.py
  tests/integration/test_openstack_one_runner.py
  tests/unit/test_charm_state.py
  tests/unit/test_openstack_manager.py
  tests/unit/test_runner_manager.py
Labels: complex, Libraries: OK

#270 Parallelize creation of OpenStack runners
  src-docs/errors.py.md
  src-docs/events.md
  src-docs/github.md
  src-docs/openstack_manager.md
  src-docs/runner.md
  src-docs/runner.py.md
  src-docs/runner_logs.md
  src-docs/runner_manager.py.md
  src-docs/shared_fs.py.md
  src-docs/storage.md
  src-docs/type.md
  src/openstack_cloud/openstack_manager.py
Labels: trivial
