Repository canonical/github-runner-operator, pull requests merged in 2024-06, with the labels that each got.

#288 OpenStack COS: Ignore openstack online runners
  src/openstack_cloud/openstack_manager.py
  tests/unit/test_openstack_manager.py
Labels: bug, trivial

#289 Log different msg in pre-job for repo-policy 5xx
  templates/pre-job.j2
Labels: bug, trivial, Libraries: OK

#292 Enable tracks for version control
  .github/workflows/promote_charm.yaml
  .github/workflows/publish_charm.yaml
Labels: trivial, Libraries: OK

#293 Openstack COS: Ignore all runners with OpenStack instances
  docs/how-to/debug-with-ssh.md
  src-docs/github.md
  src/metrics/github.py
  src/metrics/runner.py
  src/openstack_cloud/openstack_manager.py
  tests/unit/mock.py
  tests/unit/test_openstack_manager.py
Labels: bug, trivial

#291 Workaround import openstack bug
  src/openstack_cloud/__init__.py
Labels: bug, trivial, Libraries: OK

#296 Openstack: Delete keypairs on timeout
  src-docs/openstack_manager.md
  src/openstack_cloud/openstack_manager.py
Labels: bug, trivial

#297 Openstack COS: Issue metrics even if runner creation fails
  src-docs/openstack_manager.md
  src/openstack_cloud/openstack_manager.py
Labels: bug, trivial

#295 fix: key error on charm state upgrade
  .github/workflows/integration_test.yaml
  src-docs/charm_state.py.md
  src/charm_state.py
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_upgrade.py
  tests/unit/test_charm_state.py
Labels: bug, trivial, Libraries: OK

#301 Fix: config-change flushing of openstack runners
  src/charm.py
Labels: bug, trivial, urgent

#302 Fix incorrect flush condition for config-change
  src/charm.py
Labels: bug, trivial

#294 feat: passive runner deletion
  .gitignore
  src/openstack_cloud/openstack_manager.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_openstack_manager.py
Labels: trivial

#299 Docs: Fix repo runner token scope docs
  docs/reference/token-scopes.md
Labels: bug, documentation, trivial, Libraries: OK

#284 [TEST] Feat/private endpoint
  .github/workflows/e2e_test.yaml
  .github/workflows/e2e_test_openstack.yaml
  .github/workflows/e2e_test_run.yaml
  .github/workflows/integration_test.yaml
  .github/workflows/manual_test_env.yaml
  .github/workflows/test.yaml
  pyproject.toml
  scripts/setup-lxd.sh
  src-docs/charm_state.py.md
  src/charm_state.py
  src/openstack_cloud/openstack_manager.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/data/clouds.yaml.tmpl
  tests/integration/helpers/common.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_base_image.py
  tests/integration/test_charm_fork_repo.py
  tests/integration/test_charm_lxd_runner.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_runner.py
  tests/integration/test_charm_upgrade.py
  tests/integration/test_e2e.py
  tests/integration/test_openstack_base_image.py
  tests/integration/test_openstack_one_runner.py
  tests/integration/test_openstack_runner.py
  tests/unit/test_charm.py
  tests/unit/test_openstack_manager.py
Labels: Libraries: OK
