Repository canonical/github-runner-operator, pull requests merged in 2025-02, with the labels that each got.

#441 Some fixes for integration tests
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  src/charm.py
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/test_charm_upgrade.py
  tests/integration/test_debug_ssh.py
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
Labels: trivial, Libraries: Out of sync

#444 Use latest image-builder with external build
  tests/integration/conftest.py
Labels: Libraries: Out of sync

#445 Add timestamp to the logs
  .github/workflows/integration_test.yaml
  github-runner-manager/tests/integration/test_charm.py
Labels: trivial, Libraries: Out of sync

#447 Put a timeout to integration tests
  .github/workflows/integration_test.yaml
  tests/integration/helpers/common.py
Labels: trivial, Libraries: Out of sync

#432 Add TICS code quality analysis workflow
  .github/workflows/tics.yaml
Labels: trivial, Libraries: Out of sync

#439 Diagrams
  README.md
  docs/explanation/charm-architecture.md
Labels: documentation, Libraries: Out of sync

#451 Update TICS workflow
  .github/workflows/tics.yaml
  .gitignore
  tox.ini
Labels: trivial

#453 Use concurrency group to limit TICS workflow concurrency
  .github/workflows/tics.yaml
Labels: trivial, Libraries: Out of sync

#428 Move Allure-pytest to tox.ini
  requirements.txt
  tox.ini
Labels: trivial, Libraries: Out of sync

#456 use self-hosted for tics
  .github/workflows/tics.yaml
Labels: trivial

#455 Bump pyopenssl and cryptography version
  requirements.txt
Labels: Libraries: Out of sync

#452 Isd 2988 add new config options to the charm maintaining backward compatibility
  .github/workflows/e2e_test.yaml
  charmcraft.yaml
  config.yaml
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  github-runner-manager/tox.ini
  src/charm.py
  src/charm_state.py
  tests/integration/conftest.py
  tests/unit/factories.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_runner_scaler.py
Labels: Libraries: Out of sync, senior-review-required

#450 Standalone manager application CLI entrypoint and configurations.
  github-runner-manager/requirements.txt
  github-runner-manager/src/github_runner_manager/cli.py
  github-runner-manager/src/github_runner_manager/cli_config.py
  github-runner-manager/tests/unit/test_cli_config.py
Labels: complex, Libraries: Out of sync

#454 Isd 2988 pass new config options to library
  base_requirements.txt
  github-runner-manager/src/github_runner_manager/configuration/__init__.py
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/configuration/github.py
  github-runner-manager/src/github_runner_manager/constants.py
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/github_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/github.py
  github-runner-manager/src/github_runner_manager/metrics/storage.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/configuration.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/reactive/process_manager.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/types_.py
  github-runner-manager/src/github_runner_manager/types_/__init__.py
  github-runner-manager/src/github_runner_manager/types_/github.py
  github-runner-manager/tests/unit/metrics/test_storage.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/reactive/test_process_manager.py
  github-runner-manager/tests/unit/reactive/test_runner_manager.py
  github-runner-manager/tests/unit/test_github_client.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  github-runner-manager/tests/unit/test_types_.py
  github-runner-manager/tests/unit/types_/__init__.py
  requirements.txt
  src/charm.py
  src/charm_state.py
  src/factories.py
  tests/integration/helpers/openstack.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_factories.py
  tox.ini
Labels: Libraries: Out of sync, senior-review-required

#462 Simplify interface of the charm with the library
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/constants.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/src/github_runner_manager/reactive/types_.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  src/charm.py
  src/factories.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_charm.py
  tests/unit/test_factories.py
Labels: Libraries: Out of sync, senior-review-required

#466 Use Just-In-Time tokens for GitHub runner registration
  .github/workflows/test.yaml
  .github/workflows/test_github_runner_manager.yaml
  github-runner-manager/src/github_runner_manager/constants.py
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/github_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/src/github_runner_manager/reactive/types_.py
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/test_github_client.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/mock_runner_managers.py
Labels: Libraries: Out of sync, senior-review-required

#467 Add 48 to snap refresh and show in expected quantity the base_quantity
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
Labels: trivial, Libraries: Out of sync

#460 Print metrics in update_status
  src/charm.py
  tests/integration/conftest.py
Labels: trivial, Libraries: Out of sync
