Repository canonical/github-runner-operator, pull requests merged in 2025-05, with the labels that each got.

#532 Feat/app check runner
  github-runner-manager/src/github_runner_manager/http_server.py
  github-runner-manager/tests/unit/test_http_server.py
  src/charm.py
  src/errors.py
  src/manager_client.py
  src/manager_service.py
  tests/unit/test_charm.py
  tests/unit/test_manager_client.py
Labels: complex, Libraries: Out of sync

#539 feat: job manager without github configs
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/platform/multiplexer_provider.py
  github-runner-manager/src/github_runner_manager/reactive/types_.py
  github-runner-manager/tests/unit/platform/test_multiplexer_provider.py
  src/charm_state.py
  src/factories.py
  tests/integration/test_jobmanager.py
  tests/unit/test_charm_state.py
  tests/unit/test_factories.py
  tox.ini
Labels: Libraries: Out of sync, senior-review-required

#541 Fix uninstallation of package
  src/charm.py
  src/manager_service.py
Labels: Libraries: Out of sync

#538 Platform health checks
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/local-lxd/explanation/charm-architecture.md
  github-runner-manager/src/github_runner_manager/errors.py
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/models.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/github.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/health_checks.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/github_provider.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/src/github_runner_manager/platform/multiplexer_provider.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/src/github_runner_manager/types_/github.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/metrics/test_github.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_health_checks.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/platform/test_github_provider.py
  github-runner-manager/tests/unit/platform/test_jobmanager_provider.py
  github-runner-manager/tests/unit/platform/test_multiplexer_provider.py
  github-runner-manager/tests/unit/reactive/test_runner_manager.py
  github-runner-manager/tests/unit/test_github_client.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  src/charm.py
  src/errors.py
  tests/integration/conftest.py
  tests/integration/test_charm_runner.py
  tests/integration/test_jobmanager.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/mock.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync, senior-review-required

#545 [FIX] Add HTTP proxies setting for installation
  src/charm.py
  src/charm_state.py
  tests/unit/test_charm_state.py
Labels: bug, complex, Libraries: Out of sync

#547 Fix reconcile delete
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
Labels: bug

#548 Catch validation exceptions in jobmanager
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
Labels: trivial, Libraries: Out of sync

#549 Some major improvements and fixes
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/multiplexer_provider.py
  github-runner-manager/src/github_runner_manager/repo_policy_compliance_client.py
  github-runner-manager/tests/unit/platform/test_multiplexer_provider.py
  src/charm.py
  tests/integration/test_reactive.py
Labels: bug, Libraries: Out of sync

#540 Feat/app logging
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/cli.py
  github-runner-manager/src/github_runner_manager/http_server.py
  github-runner-manager/src/github_runner_manager/reconcile_service.py
  github-runner-manager/tests/integration/conftest.py
  github-runner-manager/tests/integration/helper.py
  github-runner-manager/tests/integration/test_cli.py
  src/logrotate.py
  src/manager_service.py
  tests/integration/helpers/common.py
  tests/integration/test_charm_no_runner.py
  tests/unit/test_charm.py
  tests/unit/test_logrotate.py
  tests/unit/test_manager_service.py
Labels: Libraries: Out of sync

#558 feat: custom pre-job script
  config.yaml
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  github-runner-manager/src/github_runner_manager/templates/pre-job.j2
  src/charm_state.py
  src/factories.py
  tests/integration/conftest.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_runner.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_charm_state.py
Labels: Libraries: Out of sync, senior-review-required, urgent
