Repository canonical/github-runner-operator, pull requests merged in 2025-07, with the labels that each got.

#580 Forward arbitrary TCP traffic using aproxy
  .github/workflows/e2e_test_run.yaml
  config.yaml
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  src/charm_state.py
  src/factories.py
  src/models.py
  tests/integration/conftest.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/conftest.py
  tests/unit/test_charm_state.py
Labels: Libraries: Out of sync, senior-review-required

#591 fix: Specify compute api dynamically
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_runner.py
Labels: bug, Libraries: Out of sync

#586 [ISD-3791] Fix: Add timeouts for ghapi calls
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/tests/unit/test_github_client.py
Labels: Libraries: Out of sync, senior-review-required

#593 Fix the default value of the aproxy-exclude-addresses configuration
  config.yaml
  docs/changelog.md
Labels: Libraries: Out of sync

#595 [ISD-3570] Flush runner will kill reactive processes as well
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/reactive/process_manager.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/tests/unit/reactive/test_process_manager.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  src/charm.py
  tests/integration/jobmanager/test_jobmanager_reactive.py
  tests/unit/test_charm.py
Labels: Libraries: Out of sync

#588 feat: parallel deletion of runners
  github-runner-manager/pyproject.toml
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/models.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/github_provider.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/tests/unit/factories/metrics_factory.py
  github-runner-manager/tests/unit/factories/runner_instance_factory.py
  github-runner-manager/tests/unit/fake_runner_managers.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/metrics/test_runner.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/platform/test_github_provider.py
  github-runner-manager/tests/unit/test_runner_scaler.py
Labels: complex, Libraries: Out of sync

#596 [ISD-3853] Fix: add retry limit for reactive jobs
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/tests/unit/reactive/test_consumer.py
  github-runner-manager/tests/unit/test_runner_scaler.py
Labels: bug, complex, senior-review-required

#601 chore: print application version on startup
  .github/pull_request_template.md
  github-runner-manager/pyproject.toml
  github-runner-manager/src/github_runner_manager/cli.py
Labels: trivial

#602 [ISD-3842] Fix: increase timeout for flush runner
  docs/changelog.md
  src/manager_client.py
Labels: bug, complex, senior-review-required

#605 chore: rename cleanup function
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
Labels: trivial
