Repository canonical/github-runner-operator, pull requests merged in 2025-08, with the labels that each got.

#610 test: fix rate limit update
  tests/integration/conftest.py
Labels: trivial

#608 chore: rename cloud runner instance [DO NOT MERGE WITHOUT CHANGING BASE TO MAIN]
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/vm_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/unit/factories/runner_instance_factory.py
  github-runner-manager/tests/unit/fake_runner_managers.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/test_runner_scaler.py
Labels: trivial

#609 chore: refactor vm health [DO NOT MERGE WITHOUT CHANGING BASE TO MAIN]
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/vm_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/unit/factories/runner_instance_factory.py
Labels: trivial

#616 Re-check Vale and fix errors
  .custom_wordlist.txt
  CONTRIBUTING.md
  README.md
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/explanation/security.md
  docs/explanation/ssh-debug.md
  docs/how-to/integrate-with-cos.md
  docs/how-to/openstack-runner.md
  docs/how-to/reactive.md
  docs/index.md
  docs/local-lxd/explanation/arm64.md
  docs/local-lxd/explanation/charm-architecture.md
  docs/local-lxd/explanation/ssh-debug.md
  docs/local-lxd/how-to/integrate-with-cos.md
  docs/local-lxd/reference/cos.md
  docs/local-lxd/reference/cryptographic-overview.md
  docs/local-lxd/reference/external-access.md
  docs/local-lxd/reference/integrations.md
  docs/local-lxd/reference/token-scopes.md
  docs/local-lxd/tutorial/quick-start.md
  docs/reference/cos.md
  docs/reference/cryptographic-overview.md
  docs/reference/external-access.md
  docs/reference/integrations.md
  docs/reference/token-scopes.md
  github-runner-manager/README.md
  terraform/charm/README.md
  terraform/product/README.md
Labels: documentation

#614 feat: runner metrics
  github-runner-manager/src/github_runner_manager/metrics/labels.py
  github-runner-manager/src/github_runner_manager/metrics/reconcile.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/test_prometheus_metrics.py
Labels: trivial

#621 chore: rename get vms
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/vm_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/unit/fake_runner_managers.py
  tests/integration/jobmanager/helpers.py
  tests/integration/jobmanager/test_jobmanager_prespawned.py
Labels: trivial

#624 chore: separate cleanup delete flush
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/tests/unit/fake_runner_managers.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
Labels: complex

#625 Add log level configuration for the github runner manager service
  config.yaml
  docs/changelog.md
  github-runner-manager/pyproject.toml
  github-runner-manager/src/github_runner_manager/cli.py
  src/charm_state.py
  src/manager_service.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/test_charm_state.py
Labels: senior-review-required

#620 feat(docs): Evolve and standardize the documentation workflow
  .github/workflows/docs.yaml
  .gitignore
  .licenserc.yaml
  .vale.ini
  .vale/styles/config/vocabularies/local/accept.txt
  CONTRIBUTING.md
  Makefile
  Makefile.docs
  README.md
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/how-to/integrate-with-cos.md
  docs/how-to/reactive.md
  docs/index.md
  docs/local-lxd/how-to/configure-runner-storage.md
  docs/local-lxd/how-to/integrate-with-cos.md
  docs/local-lxd/how-to/run-on-lxd.md
  docs/local-lxd/reference/cryptographic-overview.md
  docs/local-lxd/reference/external-access.md
  docs/local-lxd/tutorial/managing-resource-usage.md
  docs/local-lxd/tutorial/quick-start.md
  docs/reference/cryptographic-overview.md
  docs/reference/external-access.md
  jobmanager/client/.gitignore
Labels: documentation

#615 feat: prometheus metrics for deletion
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/metrics/reconcile.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  tests/integration/test_prometheus_metrics.py
Labels: trivial
