Repository canonical/github-runner-operator, pull requests merged in 2025-03, with the labels that each got.

#469 Some refactors to prepare for reactive / non-reactive combination
  README.md
  config.yaml
  docs/how-to/openstack-runner.md
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/github_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/models.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  github-runner-manager/src/github_runner_manager/metrics/storage.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/health_checks.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/types_/github.py
  github-runner-manager/tests/unit/manager/test_models.py
  github-runner-manager/tests/unit/metrics/test_runner.py
  github-runner-manager/tests/unit/metrics/test_storage.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/reactive/test_consumer.py
  github-runner-manager/tests/unit/test_github_client.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  github-runner-manager/tests/unit/types_/__init__.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/helpers/charm_metrics.py
  tests/integration/helpers/common.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_runner.py
  tests/integration/test_charm_upgrade.py
  tests/integration/test_reactive.py
  tests/unit/mock_runner_managers.py
Labels: Libraries: Out of sync, senior-review-required

#476 Fix backward compatibility in instance names
  github-runner-manager/src/github_runner_manager/manager/models.py
  github-runner-manager/tests/unit/manager/test_models.py
Labels: bug, Libraries: Out of sync

#475 Fix delete offline in github when building reactive
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/github_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/src/github_runner_manager/types_/github.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/test_github_client.py
  tests/integration/test_reactive.py
Labels: Libraries: Out of sync

#480 Remove usage of local filesystem for metrics from runners.
  github-runner-manager/src/github_runner_manager/errors.py
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  github-runner-manager/src/github_runner_manager/metrics/runner_logs.py
  github-runner-manager/src/github_runner_manager/metrics/storage.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/constants.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/unit/factories/openstack_factory.py
  github-runner-manager/tests/unit/metrics/test_runner.py
  github-runner-manager/tests/unit/metrics/test_runner_logs.py
  github-runner-manager/tests/unit/metrics/test_storage.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  src/charm_state.py
  src/errors.py
  tests/integration/helpers/charm_metrics.py
Labels: Libraries: Out of sync, senior-review-required

#463 Refactor/manager application threading
  github-runner-manager/pyproject.toml
  github-runner-manager/requirements.txt
  github-runner-manager/src/github_runner_manager/cli.py
  github-runner-manager/src/github_runner_manager/errors.py
  github-runner-manager/src/github_runner_manager/http_server.py
  github-runner-manager/src/github_runner_manager/reconcile_service.py
  github-runner-manager/tests/integration/conftest.py
  github-runner-manager/tests/integration/helper.py
  github-runner-manager/tests/integration/test_charm.py
  github-runner-manager/tests/integration/test_cli.py
  github-runner-manager/tests/unit/test_http_server.py
  github-runner-manager/tox.ini
Labels: complex, Libraries: Out of sync

#490 Do not crash the manager on github failure
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/tests/unit/test_github_client.py
  src/charm.py
Labels: trivial, Libraries: Out of sync

#491 Fix TIOBE TiCS framework issues.
  .github/workflows/tics.yaml
  requirements.txt
Labels: Libraries: Out of sync

#486 Terraform code for the charm
  docs/changelog.md
  terraform/.gitignore
  terraform/charm/README.md
  terraform/charm/main.tf
  terraform/charm/outputs.tf
  terraform/charm/variables.tf
  terraform/charm/versions.tf
  terraform/product/README.md
  terraform/product/main.tf
  terraform/product/outputs.tf
  terraform/product/variables.tf
  terraform/product/version.tf
Labels: trivial, Libraries: Out of sync

#489 Add security documentation
  docs/changelog.md
  docs/explanation/security.md
  docs/how-to/comply-security.md
  docs/how-to/openstack-runner.md
  docs/how-to/repo-policy.md
  docs/index.md
Labels: documentation, trivial, Libraries: Out of sync

#495 Minor improvements to terraform
  terraform/product/outputs.tf
Labels: trivial, Libraries: Out of sync

#492 Use of proxy for github runners
  .github/workflows/e2e_test.yaml
  .github/workflows/integration_test.yaml
  config.yaml
  docs/changelog.md
  github-runner-manager/pyproject.toml
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/templates/env.j2
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  github-runner-manager/tests/integration/conftest.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/test_config.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  github-runner-manager/tests/unit/test_types_.py
  scripts/setup-integration-tests.sh
  src/charm_state.py
  src/factories.py
  tests/integration/conftest.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_charm_state.py
  tests/unit/test_factories.py
Labels: Libraries: Out of sync, senior-review-required

#497 Handle thread crashes for the github-runner-manager application
  github-runner-manager/src/github_runner_manager/cli.py
  github-runner-manager/src/github_runner_manager/thread_manager.py
  github-runner-manager/tests/unit/test_thread_manager.py
  src/charm.py
  tests/integration/test_runner_manager_openstack.py
Labels: Libraries: Out of sync, senior-review-required
