Repository canonical/github-runner-operator, pull requests merged in 2025-06, with the labels that each got.

#561 feat: github-runner-manager service for reconcilations
  actions.yaml
  config.yaml
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/cli.py
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/http_server.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/reactive/process_manager.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/src/github_runner_manager/reconcile_service.py
  github-runner-manager/tests/integration/conftest.py
  github-runner-manager/tests/integration/test_cli.py
  github-runner-manager/tests/unit/conftest.py
  github-runner-manager/tests/unit/reactive/test_runner_manager.py
  github-runner-manager/tests/unit/test_config.py
  github-runner-manager/tests/unit/test_http_server.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  src/charm.py
  src/charm_state.py
  src/errors.py
  src/event_timer.py
  src/factories.py
  src/manager_client.py
  src/manager_service.py
  templates/dispatch-event.service.j2
  templates/dispatch-event.timer.j2
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/helpers/openstack.py
  tests/integration/test_charm_fork_path_change.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_runner.py
  tests/integration/test_debug_ssh.py
  tests/integration/test_jobmanager.py
  tests/integration/test_reactive.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_charm_state.py
  tests/unit/test_event_timer.py
  tests/unit/test_factories.py
  tests/unit/test_manager_client.py
  tests/unit/test_manager_service.py
Labels: complex, Libraries: Out of sync

#565 [ISD-3689] Fix: metric log owner on upgrade
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/reconcile_service.py
  src/charm.py
  tests/integration/helpers/common.py
  tests/unit/test_charm.py
Labels: bug, trivial, Libraries: Out of sync

#569 fix: revert copy truncate
  CODEOWNERS
  docs/changelog.md
  src/logrotate.py
  tests/unit/test_logrotate.py
Labels: bug, Libraries: Out of sync, urgent

#579 chore: update jobmanager client
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/tests/unit/platform/test_jobmanager_provider.py
  jobmanager/client/.openapi-generator/FILES
  jobmanager/client/README.md
  jobmanager/client/docs/GetRunnerHealthV1RunnerRunnerIdHealthGet200Response.md
  jobmanager/client/docs/Job.md
  jobmanager/client/docs/RegisterRunnerV1RunnerRegisterPost200Response.md
  jobmanager/client/docs/RegisterRunnerV1RunnerRegisterPostRequest.md
  jobmanager/client/docs/RunnersApi.md
  jobmanager/client/docs/Token.md
  jobmanager/client/docs/UpdateRunnerHealthV1RunnerRunnerIdHealthPutRequest.md
  jobmanager/client/docs/V1JobsJobIdHealthGet200Response.md
  jobmanager/client/docs/V1JobsJobIdHealthPutRequest.md
  jobmanager/client/docs/V1JobsJobIdPutRequest.md
  jobmanager/client/docs/V1JobsJobIdTokenPost200Response.md
  jobmanager/client/docs/V1JobsJobIdTokenPostRequest.md
  jobmanager/client/docs/V1JobsPost201Response.md
  jobmanager/client/docs/V1JobsPost201ResponseMaintenance.md
  jobmanager/client/docs/V1JobsPostRequest.md
  jobmanager/client/jobmanager_client/__init__.py
  jobmanager/client/jobmanager_client/api/runners_api.py
  jobmanager/client/jobmanager_client/configuration.py
  jobmanager/client/jobmanager_client/models/__init__.py
  jobmanager/client/jobmanager_client/models/get_runner_health_v1_runner_runner_id_health_get200_response.py
  jobmanager/client/jobmanager_client/models/job.py
  jobmanager/client/jobmanager_client/models/runner_create.py
  jobmanager/client/jobmanager_client/models/runner_health_response.py
  jobmanager/client/jobmanager_client/models/runner_health_update_response.py
  jobmanager/client/jobmanager_client/models/runner_register_response.py
  jobmanager/client/jobmanager_client/models/update_runner_health_v1_runner_runner_id_health_put_request.py
  jobmanager/client/jobmanager_client/models/v1_jobs_job_id_health_get200_response.py
  jobmanager/client/jobmanager_client/models/v1_jobs_job_id_health_put_request.py
  jobmanager/client/jobmanager_client/models/v1_jobs_job_id_put_request.py
  jobmanager/client/jobmanager_client/models/v1_jobs_job_id_token_post200_response.py
  jobmanager/client/jobmanager_client/models/v1_jobs_job_id_token_post_request.py
  jobmanager/client/jobmanager_client/models/v1_jobs_post201_response.py
  jobmanager/client/jobmanager_client/models/v1_jobs_post_request.py
  jobmanager/client/test/test_default_api.py
  jobmanager/client/test/test_get_runner_health_v1_runner_runner_id_health_get200_response.py
  jobmanager/client/test/test_job.py
  jobmanager/client/test/test_register_runner_v1_runner_register_post200_response.py
  jobmanager/client/test/test_register_runner_v1_runner_register_post_request.py
  jobmanager/client/test/test_runners_api.py
  jobmanager/client/test/test_token.py
  jobmanager/client/test/test_update_runner_health_v1_runner_runner_id_health_put_request.py
  jobmanager/client/test/test_v1_jobs_job_id_health_get200_response.py
  jobmanager/client/test/test_v1_jobs_job_id_health_put_request.py
  jobmanager/client/test/test_v1_jobs_job_id_put_request.py
  jobmanager/client/test/test_v1_jobs_job_id_token_post200_response.py
  jobmanager/client/test/test_v1_jobs_job_id_token_post_request.py
  jobmanager/client/test/test_v1_jobs_post201_response.py
  jobmanager/client/test/test_v1_jobs_post201_response_maintenance.py
  jobmanager/client/test/test_v1_jobs_post_request.py
  jobmanager/openapi-generate-jobmanager.sh
  tests/integration/jobmanager/helpers.py
  tests/integration/jobmanager/test_jobmanager_prespawned.py
  tests/integration/jobmanager/test_jobmanager_reactive.py
Labels: bug, trivial, Libraries: Out of sync

#575 chore: let renovate ignore jobmanager test resources
  renovate.json
Labels: trivial, Libraries: Out of sync

#570 [ISD-3696] Feat: No longer wait for runner to come online during runner creation
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  tests/integration/conftest.py
  tests/integration/helpers/common.py
  tests/integration/helpers/openstack.py
  tests/integration/jobmanager/conftest.py
  tests/integration/jobmanager/test_jobmanager_prespawned.py
  tests/integration/jobmanager/test_jobmanager_reactive.py
  tests/integration/test_charm_fork_path_change.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_charm_runner.py
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
Labels: complex, Libraries: Out of sync

#581 [ISD-3751] Fix: rejecting without retry for reactive job not found.
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  tests/integration/test_reactive.py
Labels: complex, Libraries: Out of sync, senior-review-required

#584 [ISD-3759] Change the threads to daemons, and cleanup processes
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/cli.py
  src/manager_client.py
  src/manager_service.py
  tests/integration/test_reactive.py
  tests/unit/test_manager_service.py
Labels: bug, Libraries: Out of sync, senior-review-required
