Repository canonical/github-runner-operator, pull requests merged in 2025-04, with the labels that each got.

#507 Optimize get unique server
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
Labels: trivial, Libraries: Out of sync

#506 First refactor for the new platform interface for github and jobmanager
  actions.yaml
  docs/explanation/charm-architecture.md
  github-runner-manager/src/github_runner_manager/configuration/__init__.py
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/manager/github_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/github.py
  github-runner-manager/src/github_runner_manager/platform/github_provider.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/types_.py
  github-runner-manager/tests/integration/conftest.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/metrics/test_github.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/reactive/test_consumer.py
  github-runner-manager/tests/unit/test_github_client.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  github-runner-manager/tests/unit/test_types_.py
  src/charm.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_charm_state.py
Labels: Libraries: Out of sync, senior-review-required

#510 If a job is in progress, go for the following one without a new reactive process
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/tests/unit/reactive/test_consumer.py
  tests/integration/test_reactive.py
Labels: Libraries: Out of sync

#514 Increase the pool size
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
Labels: trivial, Libraries: Out of sync

#511 Refactor platform interface. Use of metadata for tagging runners.
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/models.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/events.py
  github-runner-manager/src/github_runner_manager/metrics/github.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/models.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/github_provider.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/metrics/test_github.py
  github-runner-manager/tests/unit/metrics/test_runner.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/reactive/test_consumer.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  src/charm.py
  tests/integration/conftest.py
  tests/integration/helpers/charm_metrics.py
  tests/integration/helpers/common.py
  tests/integration/test_charm_metrics_failure.py
  tests/integration/test_charm_metrics_success.py
  tests/integration/test_charm_upgrade.py
  tests/integration/test_reactive.py
  tests/integration/test_runner_manager_openstack.py
Labels: complex, Libraries: Out of sync

#498 Implement flush runner for HTTP server
  github-runner-manager/src/github_runner_manager/cli.py
  github-runner-manager/src/github_runner_manager/configuration/__init__.py
  github-runner-manager/src/github_runner_manager/configuration/base.py
  github-runner-manager/src/github_runner_manager/http_server.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/configuration.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/reactive/process_manager.py
  github-runner-manager/src/github_runner_manager/reactive/runner.py
  github-runner-manager/src/github_runner_manager/reactive/runner_manager.py
  github-runner-manager/tests/integration/conftest.py
  github-runner-manager/tests/integration/helper.py
  github-runner-manager/tests/unit/conftest.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/reactive/test_process_manager.py
  github-runner-manager/tests/unit/reactive/test_runner_manager.py
  github-runner-manager/tests/unit/test_config.py
  github-runner-manager/tests/unit/test_http_server.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  src/factories.py
  tests/integration/test_runner_manager_openstack.py
  tests/unit/test_factories.py
Labels: Libraries: Out of sync

#518 chore: renovate group:allNonMajor
  renovate.json
Labels: Libraries: Out of sync

#504 [docs] Update reactive howto with webhook router name
  docs/how-to/reactive.md
Labels: documentation, Libraries: Out of sync

#524 fix: keypair race condition
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/runner_scaler.py
  github-runner-manager/src/github_runner_manager/metrics/runner.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/models.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/tests/integration/test_cli.py
  github-runner-manager/tests/unit/metrics/test_runner.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  tests/integration/test_reactive.py
Labels: bug, Libraries: Out of sync

#527 Jobmanager cloud init
  github-runner-manager/src/github_runner_manager/manager/cloud_runner_manager.py
  github-runner-manager/src/github_runner_manager/manager/models.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_cloud.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/__init__.py
  github-runner-manager/src/github_runner_manager/platform/github_provider.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/src/github_runner_manager/platform/multiplexer_provider.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/templates/openstack-userdata.sh.j2
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_cloud.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/platform/test_jobmanager_provider.py
  github-runner-manager/tests/unit/reactive/test_consumer.py
  github-runner-manager/tests/unit/test_github_client.py
  jobmanager/client/docs/V1JobsJobIdHealthGet200Response.md
  jobmanager/client/jobmanager_client/models/v1_jobs_job_id_health_get200_response.py
  jobmanager/client/test/test_v1_jobs_job_id_health_get200_response.py
  jobmanager/openapi-generate-jobmanager.sh
  jobmanager/openapi.yaml
  tests/integration/conftest.py
  tests/integration/helpers/openstack.py
  tests/integration/test_jobmanager.py
Labels: Libraries: Out of sync, senior-review-required

#536 Feat/isd 3149/adding how to landing page
  docs/changelog.md
  docs/how-to/index.md
  docs/index.md
Labels: documentation, trivial, Libraries: Out of sync

#535 add job share to dashboard
  docs/changelog.md
  docs/reference/cos.md
  src/grafana_dashboards/metrics.json
Labels: trivial, Libraries: Out of sync

#530 Feat/app integration
  src/charm.py
  src/errors.py
  src/manager_service.py
  tests/integration/test_charm_no_runner.py
  tests/integration/test_jobmanager.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_factories.py
  tests/unit/test_manager_service.py
Labels: complex, Libraries: Out of sync

#534 Remove SSH creation health checks
  docs/changelog.md
  github-runner-manager/src/github_runner_manager/errors.py
  github-runner-manager/src/github_runner_manager/github_client.py
  github-runner-manager/src/github_runner_manager/manager/runner_manager.py
  github-runner-manager/src/github_runner_manager/openstack_cloud/openstack_runner_manager.py
  github-runner-manager/src/github_runner_manager/platform/github_provider.py
  github-runner-manager/src/github_runner_manager/platform/jobmanager_provider.py
  github-runner-manager/src/github_runner_manager/platform/multiplexer_provider.py
  github-runner-manager/src/github_runner_manager/platform/platform_provider.py
  github-runner-manager/src/github_runner_manager/reactive/consumer.py
  github-runner-manager/src/github_runner_manager/types_/github.py
  github-runner-manager/tests/unit/manager/test_runner_manager.py
  github-runner-manager/tests/unit/mock_runner_managers.py
  github-runner-manager/tests/unit/openstack_cloud/test_openstack_runner_manager.py
  github-runner-manager/tests/unit/platform/test_github_provider.py
  github-runner-manager/tests/unit/platform/test_jobmanager_provider.py
  github-runner-manager/tests/unit/test_github_client.py
  github-runner-manager/tests/unit/test_runner_scaler.py
  tests/integration/helpers/charm_metrics.py
  tests/integration/test_jobmanager.py
Labels: Libraries: Out of sync, senior-review-required
